version: '3.8'

services:
  backend:
    build:
      dockerfile: platform/Dockerfile
      context: .
    env_file: .env
    command: ["npm", "run", "build:watch"]
    volumes:
      - ./src:/app/src/
    ports:
      - 3000:${PORT}

networks:
  default:
    external: true
    name: leadsforce