version: '3.8'

services:
  backend:
    build:
      dockerfile: platform/Dockerfile
      context: ../
    env_file: ../.env
    command: ["npm", "run", "build:watch"]
    volumes:
      - ../src:/app/src/
    ports:
      - 8080:8080
  
  meili:
    image: getmeili/meilisearch
    container_name: meili
    ports:
      - 7700:7700

networks:
  default:
    external: true
    name: leadsforce